DELETE http://localhost:3003/api/procedures/25
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9ibG8iLCJpZCI6NywiaWF0IjoxNjU3NjQ5MjQ2fQ.HGCL376ydlg0Oqk9l-S8seuDJPvwUoRHlru4hIzW8Fg