GET http://localhost:3003/api/analysis/procs-by-users?start=Sat Jan 01 2022 00:00:00 GMT+0100 (Central European Standard Time)&end=Wed Jul 20 2022 21:32:46 GMT 0200 (Central European Summer Time)
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNlY28iLCJpZCI6NSwiaWF0IjoxNjU4MzQ2Njg1fQ.QXKeFAq2HdUjekrQ2FkuZYTdq-HsJTqzyfCxWu-81aE