DELETE http://localhost:3003/api/notifications/241
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNlY28iLCJpZCI6MSwiaWF0IjoxNjU3MzYwODU0fQ.HDIGNmKZU5y1emw2aRTdy-D05Es25sfHJSE5mqFTiCc