DELETE http://localhost:3003/api/notifications/274
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNlY28iLCJpZCI6NSwiaWF0IjoxNjU4MTg5ODc3fQ.w4_ysgwbDmstZy4F39AkP0H8batKNbE6TGSrQqg8u_k