DELETE http://localhost:3003/api/authorities/1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNlY28iLCJpZCI6MywiaWF0IjoxNjUzMjQ2ODI5fQ.s_On8LfJh5b6zicD2oxhOtzlYm4WhZyU2r_wRa0NlgU